# Generated by Django 4.2 on 2025-03-02 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order_management', '0002_alter_client_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='SettingsManager',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('telegram_token', models.CharField(max_length=255, verbose_name='Токен Telegram бота')),
                ('telegram_chat_id', models.CharField(max_length=100, verbose_name='ID чата Telegram')),
                ('vk_token', models.CharField(max_length=255, verbose_name='Токен ВКонтакте')),
            ],
            options={
                'verbose_name': 'Настройки',
                'verbose_name_plural': 'Настройки',
            },
        ),
        migrations.CreateModel(
            name='ShortLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('original_url', models.URLField(max_length=2000, verbose_name='Оригинальная ссылка')),
                ('short_code', models.CharField(max_length=10, unique=True, verbose_name='Короткий код')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
            ],
            options={
                'verbose_name': 'Короткая ссылка',
                'verbose_name_plural': 'Короткие ссылки',
                'ordering': ['-created_at'],
            },
        ),
    ]
