# Generated by Django 4.2 on 2025-02-24 14:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cake',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('levels', models.IntegerField(choices=[(1, '1 уровень (+400р)'), (2, '2 уровня (+750р)'), (3, '3 уровня (+1100р)')], verbose_name='Количество уровней')),
                ('shape', models.CharField(choices=[('circle', 'Круг'), ('square', 'Квадрат'), ('rectangle', 'Прямоугольник')], max_length=20, verbose_name='Форма')),
                ('topping', models.CharField(choices=[('none', 'Без'), ('white_sauce', 'Белый соус'), ('caramel_syrup', 'Карамельный'), ('maple_syrup', 'Кленовый'), ('blueberry_syrup', 'Черничный'), ('milk_chocolate', 'Молочный шоколад'), ('strawberry_syrup', 'Клубничный')], max_length=20, verbose_name='Топпинг')),
                ('berries', models.IntegerField(blank=True, choices=[(1, 'Ежевика'), (2, 'Малина'), (3, 'Голубика'), (4, 'Клубника')], null=True, verbose_name='Ягоды')),
                ('decor', models.IntegerField(blank=True, choices=[(1, 'Фисташки'), (2, 'Безе'), (3, 'Фундук'), (4, 'Пекан'), (5, 'Маршмеллоу'), (6, 'Марципан')], null=True, verbose_name='Декор')),
                ('inscription', models.CharField(blank=True, max_length=200, null=True, verbose_name='Надпись')),
            ],
            options={
                'verbose_name': 'Торт',
                'verbose_name_plural': 'Торты',
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Имя клиента')),
                ('phone', models.CharField(max_length=20, unique=True, verbose_name='Телефон')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='Email')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата регистрации')),
            ],
            options={
                'verbose_name': 'Клиент',
                'verbose_name_plural': 'Клиенты',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(max_length=200, verbose_name='Адрес доставки')),
                ('comment', models.TextField(blank=True, null=True, verbose_name='Комментарий к заказу')),
                ('delivery_date', models.DateField(verbose_name='Дата доставки')),
                ('delivery_time', models.TimeField(verbose_name='Время доставки')),
                ('total_price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Итоговая цена')),
                ('status', models.CharField(choices=[('new', 'Новый'), ('confirmed', 'Подтвержден'), ('preparing', 'Готовится'), ('delivered', 'Доставлен'), ('canceled', 'Отменен')], default='new', max_length=20, verbose_name='Статус заказа')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата заказа')),
                ('cake', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='order_management.cake', verbose_name='Торт')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='order_management.client', verbose_name='Клиент')),
            ],
            options={
                'verbose_name': 'Заказ',
                'verbose_name_plural': 'Заказы',
                'ordering': ['-created_at'],
            },
        ),
    ]
